### PR TITLE
Carthage Support

### PR DESCRIPTION
**Pull request by alexpopov**
I had to restructure the directory structure a little bit, and tested both creating a new CocoaPods project and a new Carthage project with my fork. 

I had to add a pair of compiler directives for `SSZipArchive` and `UIMenuItem_CXAImageSupport`;
- `SSZipArchive` drops the module prefix when installed through Carthage
- `UIMenuItem_CXAImageSupport` doesn't seem to be the same between CocoaPods and Carthage so I changed the initializer depending on whether CocoaPods or Carthage is used. 

There is one final caveat: I had to add Carthage support to `UIMenuItem` and `ZFDragableModalTransition`, but my pull requests have not been accepted yet. When (if) they're accepted we'll need to update the FolioReader Cartfile to reference them instead of my forks (so we can keep getting upstream updates). 

That said, UIMenuItem is deprecated, so it may also be wise to update to the latest version of that (I added Carthage support to that one as well, also not merged yet).

### CODE REVIEW

**Comment by hebertialmeida** [comment]
Great! Just one thing, can you update the Readme with the cartage option and installation instructions?

**Comment by hebertialmeida** [comment]
About the menu have you checked this https://github.com/cxa/MenuItemKit 
It is the same menu written in Swift, and now it has Cocoapods support, the issue #41 is about a migration.

**Comment by alexpopov** [comment]
I will update the Readme tonight; I'll bring my computer home. 

re: MenuItemKit, I actually submitted a Carthage Support PR for that too, so we can use it with Carthage 😛 It shouldn't be hard to swap in.

**Comment by alexpopov** [comment]
Okay, I updated the README and set Carthage to point to the original UIMenuItem. 
I've resolved the umbrella header warning in my UIMenuItem branch, so I submitted another PR to `cxa` for that, and the warning will go away whenever that gets accepted. 

I also updated the Carthage scheme to deploy to 8.0 

There is a problem right now, `JSQWebViewController` intermittently times-out while building; that's not an issue on our end, it's is most likely a bug in Carthage; I'll create an issue for it.

**Pull request merged**
