### PR TITLE
Fix audio 'scroll to element' for horizontal

### PR DESCRIPTION
**Pull request by kjantzer**
Tested on both books.

### CODE REVIEW

**Comment by hebertialmeida** [comment]
Hey I tested and worked perfectly for horizontal, but for vertical scroll it is not working for me, I have tried but seems that there is something wrong. May we have to check  the direction and do only one direction scroll. What do you think?

**Comment by hebertialmeida** [comment]
I have being playing with some code, I found a solution based on your code. I don't know if it is the best way to handle this:

```
function goToEl(el) {
    var top = document.body.scrollTop;
    var elTop = el.offsetTop - 20;
    var bottom = window.innerHeight + document.body.scrollTop;
    var elBottom = el.offsetHeight + el.offsetTop + 60

    var clientWidth = document.documentElement["clientWidth"];
    var scrollWidth = document.body["scrollWidth"];

    if (scrollWidth > clientWidth) {
        var elLeft = document.body.clientWidth * Math.floor(el.offsetTop / window.innerHeight);
        document.body.scrollLeft = elLeft;
    } else if(elBottom > bottom || elTop < top) {
        document.body.scrollTop = el.offsetTop - 20
    }

    return el;
}
```

It is working for both orientations.

**Comment by kjantzer** [comment]
I was just finishing up testing my fix too.

I just added this before setting scroll left:

```
if( document.body.scrollTop == 0 ){
```

**Comment by hebertialmeida** [comment]
Perfect! Much better solution as always 👍

**Pull request merged**
