### PR TITLE
Changed dependencies to work with iOS 12.1 and Xcode 10.1

### PR DESCRIPTION
**Pull request by fantim**
Old dependencies causes issues with latest versions of iOS and Xcode. Updating dependencies should fix these issues without breaking functionality.

### CODE REVIEW

**Review by hebertialmeida — CHANGES_REQUESTED** [review]
Thanks @fantim the CI is failing and I believe that it is because `FolioReaderKit/Example/Podfile.lock`. Can you check that?

**Comment by fantim** [comment]
Hi @hebertialmeida , I have updated the Podlock.lock as well as updated the Cartfile. 
Travis fails with 
> value of type '[AEXMLElement]' has no member 'compactMap''

though this may be due to an older version of xcode being used in the test (9.2). An update to xcode 9.3 or higher per https://github.com/tadija/AEXML/issues/147 should fix this particular issue.

**Comment by hebertialmeida** [comment]
Weird, my if you update the Xcode version https://github.com/FolioReader/FolioReaderKit/blob/master/.travis.yml#L1

**Comment by fantim** [comment]
Hi @hebertialmeida , I changed the tests to reflect the current version of iOS as well as fixed a bug I found when running simulator. Should pass CI now!

**Comment by hameed444** [comment]
Hi. I am having problem with xcode 10.x and ios 12.1. swift 4.2
screen shot 2019-01-14 at 3 00 24 pm

**Comment by fantim** [comment]
Hi @hebertialmeida , previous version iteration of fixes would allow code to work on 12.1 on Xcode 10.1, but would was not converted to Swift 4.2

Newest commit converts to Swift 4.2, fixes some issues related to the conversion, passes Travis, and should work on a clean pod install under Examples folder.

Tested running on Mojave 10.14.2 running Xcode 10.1.
Tested Examples running on XR, iPad Air 2, iPad Pro 3rd Gen
Tested fonts changing, text to speech, night mode, scroll left to right and up to down, font size

**Comment by ghost** [comment]
@hebertialmeida any plans to merge this and release new update? FolioReaderKit is bringing in lots of dependencies, since FolioReaderKit is not frequently updated, we are running into lots of problems. Please consider.

**Comment by pardeepBishnoi029** [comment]
Book Search Option is not available in iOS. Please suggest me when this feature is coming in iOS.

**Review by AmarinderChahal — APPROVED** [review]
After deintegrating, cleaning, and installing the pods again, the code in the PR works for me.

**Comment by freakymaulana** [comment]
> After deintegrating, cleaning, and installing the pods again, the code in the PR works for me.

maybe you can explain for the detail, because just now I try to install with pod install still have a problem. thanks bro

**Review by hebertialmeida — APPROVED** [review]
Everything looking good... Thanks @fantim!!!

**Comment by AmarinderChahal** [comment]
> maybe you can explain for the detail, because just now I try to install with pod install still have a problem. thanks bro

@freakymaulana I will use the example project provided in this repository for reference. I also use [pod deintegrate](https://github.com/CocoaPods/cocoapods-deintegrate) and [pod clean](https://github.com/BendingSpoons/cocoapods-clean) for convenience. In a terminal, after navigating to the Example directory, run the following commands:

pod deintegrate
pod clean
pod install
pod update

The last command may be redundant, but is there just to be sure that all the pods are the versions we desire.

Hope this helps!

**Comment by hebertialmeida** [comment]
I have just released the 1.4.0 to Cocoapods https://github.com/FolioReader/FolioReaderKit/releases/tag/1.4.0

**Comment by fantim** [comment]
Thanks @hebertialmeida ! Hoping others will benefit from this release!

Cheers -

**Comment by hebertialmeida** [comment]
@fantim thank you so much for your contributions, it will definitely help people using it!

**Pull request merged**
