### PR TITLE
ePub 3.0 media overlays can be played and example updated to demonstrate

### LINKED ISSUE #11: Add support for ePub 3.0 "Media Overlays"
Particularly, the ability to sync audio to text.

>EPUB Media Overlays 3.0 ... [supports] representation of audio synchronized with the EPUB Content Document.  [[source]](http://www.idpf.org/epub/30/spec/epub30-mediaoverlays.html#sec-overview-purpose-and-scope)

I have begun doing some testing to implement this feature by starting with `Bridge.js`

```js
function goToID(id){
    var el = document.getElementById(id);
    document.body.scrollTop = el.offsetTop - 20
    return el;
}

function removeAudioMark(){
    var els = document.body.getElementsByClassName("audio-mark")
    if( els.length > 0 )
    for( i = 0; i <= els.length; i++){
        els[i].classList.remove("audio-mark");
    }
}

function audioMarkID(id){
    removeAudioMark();
    var el = goToID(id);
    el.classList.add("audio-mark")
}
```

```css
.audio-mark {
    background: #81D4FA;
    border-radius: 3px;
    padding-right: 4px;
    margin-right: -4px
}
```

### PR DESCRIPTION
**Pull request by kjantzer**
Closes #11 

Please test the functionality and let me know if changes are needed. I figure there will be more features added as we think of them, but this if a start at basic audio synced epubs

audio-player mov

### CODE REVIEW

**Comment by hebertialmeida** [comment]
I got some errors while building the project.

screen shot 2016-01-11 at 18 02 38

I guess that it's some epub files that are linked to the project.

screen shot 2016-01-11 at 18 04 45

**Comment by kjantzer** [comment]
Ah, yes. My bad – those were some internal company epubs I was testing. I will remove the reference

**Comment by kjantzer** [comment]
@hebertialmeida Try it now

**Comment by hebertialmeida** [comment]
Thanks!

**Pull request merged**
