### PR TITLE
Fix App crashing on iOS 13 

### PR DESCRIPTION
**Pull request by illwss**
- Fix App crashing on iOS 13  ( Must return MPRemoteCommandHandlerStatus or take a completion handler as the second argument.)
- Nav bar color
- Text View Background (HighlightNote) is clear color (iOS13, Dark mode is black)

### CODE REVIEW

**Comment by alqaimsolutions5** [comment]
Please review and merge this pull request. As app is crashing on iOS 13 on this point.

**Review by hebertialmeida — APPROVED** [review]
Thanks @illwss!

**Comment by santosh3288** [comment]
replace this function and crashed resoled
func registerCommandsIfNeeded() {

        guard !registeredCommands else { return }

        let command = MPRemoteCommandCenter.shared()
        command.previousTrackCommand.isEnabled = true
        
        command.previousTrackCommand.addTarget { [weak self] (event) -> MPRemoteCommandHandlerStatus in
                  self?.playPrevChapter()
                  return .success
              }
        command.nextTrackCommand.addTarget { [weak self] (event) -> MPRemoteCommandHandlerStatus in
                         self?.playNextChapter()
                         return .success
        }
        
        
        //command.previousTrackCommand.addTarget(self, action: #selector(playPrevChapter))
        command.nextTrackCommand.isEnabled = true
       // command.nextTrackCommand.addTarget(self, action: #selector(playNextChapter))
        
        
        command.pauseCommand.isEnabled = true
        //command.pauseCommand.addTarget(self, action: #selector(pause))
        
        command.pauseCommand.addTarget { [weak self] (event) -> MPRemoteCommandHandlerStatus in
                               self?.pause()
                               return .success
              }
        
        
        command.playCommand.isEnabled = true
        
        //command.playCommand.addTarget(self, action: #selector(play))
        
        command.playCommand.addTarget { [weak self] (event) -> MPRemoteCommandHandlerStatus in
                                     self?.play()
                                     return .success
                    }
        
        
        command.togglePlayPauseCommand.isEnabled = true
        
        command.togglePlayPauseCommand.addTarget { [weak self] (event) -> MPRemoteCommandHandlerStatus in
                                           self?.togglePlay()
                                           return .success
                          }
        
       // command.togglePlayPauseCommand.addTarget(self, action: #selector(togglePlay))

        registeredCommands = true
    }

**Comment by hebertialmeida** [comment]
@santosh3288 Can you open a PR so I can review it.

**Pull request merged**
