### PR TITLE
fixed issue #37

### PR DESCRIPTION
**Pull request by EmersonCarpes**
solution for highlight between paragraphs based on code from @ajeenats for Android

### CODE REVIEW

**Comment by gabrielvieira** [comment]
There a problem when reopen ebook and click highlight on highlight list, the problem maybe was on population highlights

**Comment by gabrielvieira** [comment]
@EmersonCarpes 

Fixed adding 

```
html = html.replacingOccurrences(of: "</p>", with: "<br><br>")
html = html.replacingOccurrences(of: "<p>", with: "")
```

after
```
let toInject = "\n\(cssTag)\n\(jsTag)\n</head>"
html = html.replacingOccurrences(of: "</head>", with: toInject)
```
in FolioReaderCenter.swift  line 407

**Comment by hebertialmeida** [comment]
@EmersonCarpes have you look at this ^^

**Review by hebertialmeida — CHANGES_REQUESTED** [review]
It works when adding the highlight, but the restore is not working 100%. Take a look on @gabrielvieira comment, seems that it fixed for me 😄

**Comment by gabrielvieira** [comment]
@hebertialmeida i tested this fix, and the "br" solution for paragraphs works well but broken the reading feature

**Pull request closed without merging**
