### PR TITLE
Better support for iPhone X and NightMode Fix

### PR DESCRIPTION
**Pull request by mgiroux**
Adds support for iPhone X regarding the PageIndicator (was hidden by the swipe home bar)
Fixes night mode glitch (white pages / white borders on pages)

### CODE REVIEW

**Comment by hebertialmeida** [comment]
Hi @mgiroux, thanks for your contribution!

I think this needs a little bit more work, I have tested it and it initially fixes the problem with iPhone X in portrait mode, but for landscape, it is not working even for the normal iPhone.

I found this iPhone X guidelines (https://developer.apple.com/ios/human-interface-guidelines/overview/iphone-x/), I think the path is to try to implement this "safe area", so it will work with any device, on any orientation.

This is how it looks like:
screen shot 2017-10-11 at 10 04 05 pm
screen shot 2017-10-11 at 10 06 01 pm

What do you think?

**Comment by hebertialmeida** [comment]
This is also related to #261

**Comment by mgiroux** [comment]
I agree that i did not look passed the portrait on iphone (cause really who reads in landscape on iphone) but i could implement the changes for that. As far as the text goes, i would have to look around and figure out where you position the view so i can fix it for iphone x. Let me know

**Comment by mgiroux** [comment]
i have implemented the fix for landscape iphone x

screen shot 2017-10-12 at 10 17 02 am
screen shot 2017-10-12 at 10 17 34 am

screen shot 2017-10-12 at 10 16 17 am
screen shot 2017-10-12 at 10 16 24 am

(iPhone 8+)

it lines up with the navigation bar. 

I commited the changes.

Also, i tried to place the reader page, but it does not like to be moved the way i did it (it would mess up page alignment and would skip full chapter when rotating back to portrait)... i might leave this one to you.

Thanks

**Comment by hebertialmeida** [comment]
Hey @mgiroux, looks like #287 have covered the Swift 4 migration and iPhone X, I have merged that and I will close this for one.

**Pull request closed without merging**
