### PR TITLE
If navbar doesn't hide on tap, it should not hide when font menu is shown

### PR DESCRIPTION
**Pull request by kjantzer**

### CODE REVIEW

**Comment by hebertialmeida** [comment]
I have to hide it because of the day/night transition effect, it looks strange with the navigationBar.

**Comment by kjantzer** [comment]
I wondered if that may have been why you did that.

I added `FolioReader.sharedInstance.readerCenter.configureNavBar()` to help this, although its not perfect because it does not animate the color change.

daynight mov

**Comment by hebertialmeida** [comment]
Yes, the animation is not smooth, so I prefer to hide. What do you think?

**Comment by kjantzer** [comment]
I really wish we could animate the navbar, but in my limited research, I did not find a way to animate `navBar?.setBackgroundImage()`

We can keep it hidden for now. The reason I changed it was because the `hideBar()` is being called when presenting the "audio controls" view and it looked weird to have the navbar hide itself. When I traced it out, I noticed it happening in the font menu view so I changed it for both. 

_I'll keep the navbar visible for the audio controls view only._

**Comment by hebertialmeida** [comment]
So I don't think I need merge this for now right?

**Comment by kjantzer** [comment]
Correct.

**Pull request closed without merging**
